server:
  port: 8082

spring:
  application:
    name: 'event-service'
  datasource:
    username: kndoni
    url: jdbc:postgresql://localhost:5433/event
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    generate-dll: true
  zipkin:
    base-url: http://localhost:9411
#  feign:
#    httpclient:
#      enabled: true
  rabbitmq:
    addresses: localhost:5672

#rabbitmq:
#  exchanges:
#    internal: internal.exchange
#  queues:
#    event: event.queue
#  routing-keys:
#    internal-event: internal.event.routing-key