server:
  port: 8081

spring:
  application:
    name: 'user-service'
  security:
    user:
      name: user
      password: user
  datasource:
    username: kndoni
    url: jdbc:postgresql://localhost:5433/user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    generate-dll: true
  zipkin:
    base-url: http://localhost:9411
#  feign:
#    httpclient:
#      enabled: true
  rabbitmq:
    addresses: localhost:5672
