apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  labels:
    app: event-service
spec:
  replicas: 1
  template:
    metadata:
      name: event-service
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: kristi98/events-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
      restartPolicy: Always
  selector:
    matchLabels:
      app: event-service
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  selector:
    app: event-service
  ports:
    - port: 8082
